name: Linux
on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '**.yml'
      - 'plat.conf'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Linux.yml'
      - 'plat.conf'


jobs:
  Docker:
    strategy:
      matrix:
        os: ["ubuntu:latest", "almalinux:latest", "opensuse/leap:latest", "alpine:latest", "oraclelinux:8", "kalilinux/kali", "archlinux:latest", "mageia", "gentoo/stage3"]
    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_ACME_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v2
    - name: Run acmetest
      run: |
        sysctl -w net.core.rmem_max=2500000
        ./rundocker.sh  testplat ${{ matrix.os }}

