name: MacOS
on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/MacOS.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/MacOS.yml'



jobs:
  MacOS:
    runs-on: macos-latest
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_ACME_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run:  brew update && brew install socat;
    - name: Run acmetest
      run: sudo --preserve-env ./letest.sh
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: logs