name: NetBSD
on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/NetBSD.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/NetBSD.yml'



jobs:
  NetBSD:
    strategy:
      matrix:
        release: [ "8.0", "9.0", ""]
    runs-on: macos-12
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_ACME_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v2
    - uses: vmactions/cf-tunnel@v0.0.3
      id: tunnel
      with:
        protocol: http
        port: 8080
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - uses: vmactions/netbsd-vm@v0
      with:
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server'
        nat: |
          "8080": "80"
        prepare: |
          pkg_add curl socat
        usesh: true
        release: ${{ matrix.release }}
        run: ./letest.sh
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: logs
